services:
  systemrejestracjiincydentw:
    image: ${DOCKER_REGISTRY-}systemrejestracjiincydentw
    build:
      context: .
      dockerfile: SystemRejestracjiIncydentów/Dockerfile
    depends_on:
      - db

  db:
    container_name: MSSQL
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123!"
    ports:
        - "1433:1433"
    volumes:
        - sqlserverdata:/var/opt/mssql
    #   - ./DB/data:/var/opt/mssql/data
    #   - ./DB/log:/var/opt/mssql/log
    #   - ./DB/secrets:/var/opt/mssql/secrets

volumes:
    sqlserverdata:
      driver: local